version: '3.3'
services:
    public:
        volumes:
            - '/rotary/public:/rotary'
        ports:
            - '80:8080'
        image: docker.io/svenstaro/miniserve
        restart: always
        command: -u -o -z -r -t "ROTARY PHONE" -c archlinux -F --hide-theme-selector /rotary

    admin:
        volumes:
            - '/rotary:/admin'
        ports:
            - '81:8081'
        image: docker.io/svenstaro/miniserve
        restart: always
        command: -u -o -z -r -a admin:R0tary123 -p 8081 -t "ROTARY PHONE ADMIN" -c archlinux -F --hide-theme-selector /admin
